version: '3.8'  # Specify the version of Docker Compose

services:
  app:  # Name of your service
    build:
      context: .  # Directory containing the Dockerfile
      dockerfile: Dockerfile  # Name of the Dockerfile (if different, specify here)
    ports:
      - "${HOST_PORT:-3001}:3000"  # Use environment variable for host port, default to 3001 if not set
